name: Deploy Chain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Compiling...
        
  DeployFeature:
    name: Deploy to Feature Dev
    if: github.event_name == 'pull_request'
    needs: Build
    runs-on: ubuntu-latest
    environment:
      name: feature development
      url: http://REV-123.evoya.com
    steps:
      - name: Deploy
        run: echo Deploying to temporary feature dev...
        
  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'push'
    needs: Build
    runs-on: ubuntu-latest
    environment:
      name: development
      url: http://dev.evoya.com
    steps:
      - name: Deploy
        run: echo Deploying to dev...
        
  DeployQa:
    name: Deploy to QA
    needs: DeployDev
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: http://qa.evoya.com
    steps:
      - name: Deploy
        run: echo Deploying to qa...
        
  DeployProd:
    name: Deploy to Production
    needs: DeployQa
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://prod.evoya.com
    steps:
      - name: Deploy
        run: echo Deploying to production...
